Add: インターン課題の資料を作成
jigintern/intern-2024-assignment pull request #2
Opened 2024-04-24 07:55 UTC by Futaba-Kosuke

## 概要

インターン課題の資料を作成しました

内容は以下です
- 課題の仕様・提出方法の概要
- ベース部分の実装〜Deno Deployへのデプロイ方法
- 必須仕様を満たすためのヒント

## 備考

2024-04-25 05:02 UTC, Futaba-Kosuke commented
こちらにhtml上がりました 🙏 
https://jigintern.github.io/intern-2024-assignment/description.html

2024-04-25 05:48 UTC, haruyuki-16278 requested changes
大体良さそうに思います、

2024-04-25 05:48 UTC, haruyuki-16278 commented on description.md
> +HTTPサーバーとは、HTTP (HyperText Transfer Protocol) でブラウザと通信するサーバーです。HTTPサーバー上に処理やデザイン等を記述することで、様々なWebアプリを動作させられます。
```suggestion
HTTPサーバーとは、HTTP (HyperText Transfer Protocol)  に則って通信するサーバーです。HTTPサーバー上に処理やデザイン等を記述することで、様々なWebアプリを動作させられます。  
```

ブラウザに限らなくても良いかもなと思いました

2024-04-26 01:02 UTC, Futaba-Kosuke commented on description.md
> +HTTPサーバーとは、HTTP (HyperText Transfer Protocol) でブラウザと通信するサーバーです。HTTPサーバー上に処理やデザイン等を記述することで、様々なWebアプリを動作させられます。
@haruyuki-16278   
こちら修正しました 🙇

2024-04-26 02:40 UTC, nabe1005 commented on description.md
> +deno server.js
MUST: `deno run server.js` だと思います

2024-04-26 02:40 UTC, nabe1005 commented on description.md
> +開発に必要な機能の多くを踏襲しており、プラグインの開発も企業・個人問わず行われているので、特に拘りが無ければインストールをおすすめします。
IMO: 踏襲 → 搭載 のほうがわかりやすいかと思います

2024-04-26 02:40 UTC, nabe1005 commented on description.md
> +```
MUST: Deno の std ライブラリの最新バージョンは、0.223.0 になります。  
こちらでは `http/server.ts` が deprecated になっています。

`Deno.serve` メソッドで代用するよう記載があります。  
以下、Deno.serve メソッドのドキュメントです。
https://deno.land/api@v1.42.4?s=Deno.serve

以降の serve 使用箇所も同様に修正していただきたいです 🙇

2024-04-26 02:40 UTC, nabe1005 commented on description.md
> +## Step 13. 実装を進めよう
IMO: Step13 の冒頭とヒント下の「おわりに」で同じようなことを記載しているのが気になりました。  
そもそもヒントの下にセクションを置く必要がないような気もするので、Step13 を「おわりに」として、「実装を進めて提出してください」という旨を記述し、ヒントはその下でStep14 とするのはどうでしょうか？

2024-04-26 02:42 UTC, nabe1005 commented
IMO: 文末に句点がある部分とない部分になっているのが気になりました。

本文、箇条書き(番号付きのものも含む)に対して、句点をつけるのかつけないのかを統一したほうがいいかと思います。

1行1文ではないので、最後の文だけ句点がないのが違和感なので、抜けているところにはつけていく対応がいいのかなと思います 🙏

2024-04-26 02:53 UTC, nabe1005 commented on description.md
> +4. 何回かアクセスして、ブラウザにアクセス回数が表示されればOKです！尚、ブラウザが自動で`/favicon.ico`を取得しようとするため、カウントが2ずつカウントアップすることがあります。
IMO: 2ずつ→2つずつ

2024-04-26 07:56 UTC, nabe1005 approved these changes
LGTM 👍

2024-04-26 08:11 UTC, haruyuki-16278 requested changes
`https://` は標準だと使えない気がします。 `http://localhost:8000` に全体を通して修正する必要がありそうです。
（うっかりhttps://でアクセスすると、chromeの分かりづらい設定をたどってhttpsの無効化をやらなきゃいけなかったはずなので、http://で開くように書いておかないと困る学生がいそうです）

2024-04-26 08:22 UTC, haruyuki-16278 commented on description.html
> +<title>description.md</title>
タイトルこれちょい微妙かも？と思いました

2024-04-26 08:28 UTC, nabe1005 commented on description.md
> +# しりとりアプリを作ってみよう！
横からすみません  

html のタブタイトルとこのタイトルは統一すべきかなと思うので、こちらも「jig.jp インターン2024 選考課題」とするのがいいかと思いました

https://github.com/jigintern/intern-2024-assignment/pull/2#discussion_r1580664132

2024-04-26 08:34 UTC, haruyuki-16278 approved these changes
その他特に気になるところはありませんでした。   
修正ありがとうございます！ :LGTM: :+1:

2024-04-26 08:47 UTC, merged